### PR TITLE
Fix ref and entity not appearing in view

### PR DESCRIPTION
**Pull request by dragoncorpgit**
Seems that setIfthenpayData() is not call after addOrderHistory()

### CODE REVIEW

**Comment by manuelrocha88** [comment]
@dragoncorpgit I've tested with the actual version and It's seems working... 

What's your opencart version, the actual issue and how can I reproduce it?

**Comment by dragoncorpgit** [comment]
Opencart 2.3.0.2 using the theme Journal
So the problem was in checkout/confirm page, the ref and entry were empty. 
I check the DB and the table ifthenpay_multibanco was empty has well.
Using the debugger I found that the setIfthenpayData() wasn't being call, seems that the
addOrderHistory() was terminating the code...

**Comment by manuelrocha88** [comment]
Strange. Maybe is a issue with the theme... I've that opencart version and is working...

Can you send a copy of the theme?

**Comment by dragoncorpgit** [comment]
A new version of theme was been release, in the changelog it says that fixes a problem with the payments methods.
So yeah it was a theme problem.
This pull can be cancel, sorry for spending your time.

**Comment by manuelrocha88** [comment]
@dragoncorpgit glad that the problem is solved. Anyway, we thank you for your contribution in trying to solve this issue, which has been created by the theme you use. 

Will close the ticket and cancel the pull

**Pull request closed without merging**
